baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Eventually'
theme = 'eventually'


[params]
pagetitle = 'PRELAUNCH'
description1 = 'A simple hugo theme for telling the world when you will launch your next big thing.'
description2 = 'This is an HTML5UP.NET template ported by MUSABBIRSAGAR.COM'
twitter = 'https://twitter.com/#'
instagram = 'https://instagram.com/#'
github = 'https://twitter.com/'
email = 'https://twitter.com/'
